default_language_version:
    python: python3.9
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml
        args:
        - --unsafe
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    files: backend/qualibrate
    hooks:
      - id: mypy
        name: Check typing
        language: system
        files: backend
#        entry: poetry -C backend run poe --root backend type
        entry: bash -c 'cd backend; poetry run poe type'

      - id: ruff-lint
        name: Linting
        language: system
        files: backend
#        entry: poetry -C backend run poe --root backend lint
        entry: bash -c 'cd backend; poetry run poe lint'
#
      - id: ruff-format
        name: Check formatting
        language: system
        files: backend
#        entry: poetry -C backend run poe --root backend format
        entry: bash -c 'cd backend; poetry run poe format'
