[tool.poetry]
name = "qualibrate-backend"
version = "0.1.0"
description = ""
authors = ["Maxim V4S <maxim.d@v4scale.com>"]
repository = "https://github.com/qua-platform/qualibrate"
packages = [
    { include = "qualibrate" }
]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
fastapi = "^0.109.0"
uvicorn = "^0.27.0.post1"

[tool.poetry.group.dev.dependencies]
mypy = "^1.8.0"
ruff = "^0.1.15"


[tool.poetry.group.test.dependencies]
pytest = "^8.0.0"
pytest-mock = "^3.12.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
