import React from "react";
// eslint-disable-next-line css-modules/no-unused-class
import styles from "./styles/LogsPanel.module.scss";
import { useRightSidePanelContext } from "../context/RightSidePanelContext";
import { CircularProgress } from "@mui/material";
import { useLogsScroll, useLogsCopy } from "./hooks";
import { LogEntry } from "./components";

export const LogsPanel: React.FC = () => {
  const { logs } = useRightSidePanelContext();
  
  const {
    panelContentRef,
    showScrollToBottom,
    handleScroll,
    scrollToBottom
  } = useLogsScroll(logs);
  
  const {
    copiedIndex,
    copyLogToClipboard
  } = useLogsCopy();

  return (
    <>
      <div className={styles.panelHeader}>
        <span className={styles.panelHeaderSpan}>LOGS</span>
      </div>
      <div 
        ref={panelContentRef}
        className={styles.panelContent}
        onScroll={handleScroll}
      >
        {logs.length === 0 ? (
          <div className={styles.emptyState}>
            <div className={styles.emptyStateIcon}>
              <CircularProgress size={48} />
            </div>
            <div className={styles.emptyStateTitle}>No logs available</div>
            <div className={styles.emptyStateDescription}>
              Logs will appear here when they are generated by the system.
            </div>
          </div>
        ) : (
          logs.map((log, index) => (
            <LogEntry
              key={`${log.name}_${index}`}
              log={log}
              index={index}
              copiedIndex={copiedIndex}
              onCopy={copyLogToClipboard}
            />
          ))
        )}
      </div>
      <button
        className={`${styles.scrollToBottomButton} ${showScrollToBottom ? styles.visible : ""}`}
        onClick={scrollToBottom}
        title="Scroll to bottom"
      >
        ↓ Latest
      </button>
    </>
  );
};
