name: Playwright Tests

on:
  push:
    branches:
      - main
      - integration
  pull_request:
    branches:
      - main
      - integration

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the main repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Use Node.js
        id: node-setup
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - uses: actions/cache@v4
        id: frontend-cache-id
        with:
          path: frontend/node_modules
          key: npm-${{ hashFiles('frontend/**/package-lock.json') }}
          restore-keys: npm-

      - name: Install npm deps
        if: steps.frontend-cache-id.outputs.cache-hit != 'true'
        working-directory: frontend
        run: npm ci

      - name: Build frontend
        working-directory: frontend
        run: npm run build

      # - name: Install poetry
      #   run: | 
      #     pipx install poetry
      #     echo "${HOME}/.local/bin" >> $GITHUB_PATH

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          # cache: "poetry"
          # cache-dependency-path: backend/poetry.lock

      - name: Copy built FE to BE
        run: cp -r frontend/dist backend/qualibrate_static

      - name: Install qualibrate-app
        poetry install

      - name: Install qualibrate-core and qualibrate-runner
        run: pip install git+https://github.com/qua-platform/qualibrate-runner.git \
          git+https://github.com/qua-platform/qualibrate-core.git

      # Checkout the private calibration scripts repository
      - name: Checkout Calibration Scripts
        uses: actions/checkout@v4
        with:
          repository: 'qua-platform/qualibrate-examples'
          path: 'qualibrate-examples'
          token: ${{ secrets.QUALIBRATION_EXAMPLES_TOKEN }}

      - name: Install Playwright Test Dependencies
        run: pip install quam xarray

      # Prepare directories and static files
      # - name: Prepare Directories
      #   run: |
      #     mkdir -p ~/.qualibrate/user_storage/my_project

      # Create Qualibrate Configuration
      - name: Create Qualibrate Configuration
        run: |
          qualibrate config --auto-accept \
            --runner-calibration-library-folder ~/qualibrate-examples/calibrations \
            --app-static-site-files ./backend/qualibrate_static \
            --app-user-storage ~/.qualibrate/user_storage
          # Uncomment the line below to debug the configuration file
          # cat ~/.qualibrate/config.toml

      # Install Node.js and Playwright
      - name: Install Playwright Dependencies
        working-directory: ./frontend/tests
        run: |
          npm install
          npx playwright install --with-deps

      # Start Qualibrate Server
      - name: Start Qualibrate Server
        run: |
          qualibrate start 

      # Verify Calibration Nodes in the UI
      - name: Verify Calibration Nodes
        run: |
          curl -s http://localhost:8001/api/calibrations | jq || echo "Calibration nodes not accessible."

      # Run Playwright Tests
      - name: Run Playwright Tests
        working-directory: ./frontend/tests/e2e
        env:
          DEBUG: pw:api
        run: |
          npx playwright test

      # Inspect Server Logs (on failure)
      # - name: Inspect Server Logs
      #   if: failure()
      #   run: |
      #     echo "Server Logs:"
      #     cat qualibrate-server.log

