name: Create release

on:
  push:
    tags:
      - v*

jobs:
  build:
    - uses: qua-platform/qualibrate-app/.github/workflows/reusable-buld.yaml@release-ci
  release:
    - uses: actions/checkout@v4
    - uses: actions/download-artifact@v4
      with:
        path: dist
        merge-multiple: true
        pattern: python-package-*
    - name: Release pushed tag
      runs-on: ubuntu-22.04
      steps:
        - name: Create release
          env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run:
            gh release create ${{ github.ref_name }}
              --generate-notes --verify-tag --latest
              --draft
              "dist/qualibrate_app-${GITHUB_REF_NAME#v}-py3-none-any.whl"
              "dist/qualibrate_app-${GITHUB_REF_NAME#v}.tar.gz"
                
