# This workflow is used for building qualibrate-app python package in dist 
# and wheel formats. It should be noted that firstly the frontend package is 
# built. And build frontend files are added to the backend package. Then the
# backand package is built. Built backend package archives is attached to 
# workflow run as artifacts. The workflow should only be automatically 
# triggered by other workflows (manual build and release).

name:
  Reusable build python package with built frontend (called by other workflows)

on:
  workflow_call
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        id: node-setup
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - uses: actions/cache@v4
        id: frontend-cache-id
        with:
          path: frontend/node_modules
          key: npm-${{ hashFiles('frontend/**/package-lock.json') }}
          restore-keys: npm-

      - name: Install npm deps
        if: steps.frontend-cache-id.outputs.cache-hit != 'true'
        working-directory: frontend
        run: npm ci

      - name: Build frontend
        working-directory: frontend
        run: npm run build
        env:
          USE_RELATIVE_PATHS: true

      - name: Install poetry
        run: pipx install poetry

      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"
          cache: "poetry"
          cache-dependency-path: backend/poetry.lock

      - name: Copy built FE to BE
        run: cp -r frontend/dist backend/qualibrate_static

      - name: Install python deps
        run: poetry install
        working-directory: backend

      - name: Build python package
        run: poetry build
        working-directory: backend

      - uses: actions/upload-artifact@v4
        id: upload-sdist
        name: Upload sdist
        with:
          name: python-package-sdist
          path: backend/dist/qualibrate_app-*.tar.gz
          retention-days: 3
          if-no-files-found: error

      - uses: actions/upload-artifact@v4
        id: upload-wheel
        name: Upload wheel
        with:
          name: python-package-wheel
          path: backend/dist/qualibrate_app-*.whl
          retention-days: 3
          if-no-files-found: error
