name: Reusable Vitest Tests

on:
  workflow_call:
    inputs:
      qualibrate-app-ref:
        description: "Name of branch for qualibrate-app repo"
        default: "main"
        required: false
        type: string

jobs:
  reusable-vitest-tests:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout qualibrate-app repository
      - name: Checkout App
        uses: actions/checkout@v4
        with:
          repository: qua-platform/qualibrate-app
          path: qualibrate-app
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ inputs.qualibrate-app-ref }}

      # Step 2: Set up Node.js
      - name: Use Node.js
        id: node-setup
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      # Step 3: Cache frontend dependencies
      - uses: actions/cache@v4
        id: frontend-cache-id
        with:
          path: qualibrate-app/frontend/node_modules
          key: npm-${{ hashFiles('qualibrate-app/frontend/**/package-lock.json') }}
          restore-keys: npm-

      # Step 4: Install frontend dependencies
      - name: Install npm dependencies
        if: steps.frontend-cache-id.outputs.cache-hit != 'true'
        working-directory: qualibrate-app/frontend
        run: npm ci

      # Step 5: Run Vitest unit tests
      - name: Run Vitest Tests
        working-directory: qualibrate-app/frontend
        run: npm test